name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 6
      matrix:
        build_configuration: [Release]
        build_platform: [x64, Win32]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild of plugin dll
      working-directory: .\
      run: msbuild DoxyIt.sln /m /p:Configuration="${{ matrix.build_configuration }}" /p:Platform="${{ matrix.build_platform }}" /target:zip
      env:
          ZIPCMD: 7z a -tzip

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
          name: DoxyIt-${{ matrix.build_configuration }}-${{ matrix.build_platform }}
          path: bin\${{ matrix.build_configuration }}\${{ matrix.build_platform }}\DoxyIt.dll

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_configuration == 'Release'
      with:
          body: ${{ github.event.commits[0].message }}
          files: bin/${{ matrix.build_configuration }}/${{ matrix.build_platform }}/DoxyIt-${{ github.ref_name }}-${{ matrix.build_platform }}.zip

    - name: SHA256
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_configuration == 'Release'
      run: sha256sum.exe bin\${{ matrix.build_configuration }}\${{ matrix.build_platform }}\DoxyIt-${{ github.ref_name }}-${{ matrix.build_platform }}.zip